'primary': 'var( --orange-a9)',
'primary-border': 'var(--orange-a10)',
'primary-hover': 'var(--orange-11)',
'primary-focus': 'var(--color-primary-focus)',
'primary-active': 'var(--color-primary-active)',

'secondary': 'var(--color-secondary)',
'secondary-border': 'var(--color-secondary-border)',
'secondary-hover': 'var(--color-secondary-hover)',
'secondary-focus': 'var(--color-secondary-focus)',
'secondary-active': 'var(--color-secondary-active)',

'success': 'var(--color-success)',
'success-border': 'var(--color-success-border)',
'success-hover': 'var(--color-success-hover)',
'success-focus': 'var(--color-success-focus)',
'success-active': 'var(--color-success-active)',

'info': 'var(--color-info)',
'info-border': 'var(--color-info-border)',
'info-hover': 'var(--color-info-hover)',
'info-focus': 'var(--color-info-focus)',
'info-active': 'var(--color-info-active)',

'warning': 'var(--color-warning)',
'warning-border': 'var(--color-warning-border)',
'warning-hover': 'var(--color-warning-hover)',
'warning-focus': 'var(--color-warning-focus)',
'warning-active': 'var(--color-warning-active)',

'danger': 'var(--color-danger)',
'danger-border': 'var(--color-danger-border)',
'danger-hover': 'var(--color-danger-hover)',
'danger-focus': 'var(--color-danger-focus)',
'danger-active': 'var(--color-danger-active)',

'light': 'var(--color-light)',
'dark': 'var(--color-dark)',
'gray': 'var(--color-gray)',
'dark-gray': 'var(--color-dark-gray)',